package da3dsoul.reference;

import cpw.mods.fml.common.*;
import java.util.*;

public class Metadata
{
    public static ModMetadata init(final ModMetadata metadata) {
        metadata.modId = "da3dsoulASMFix";
        metadata.name = "DA3DSOUL ASM Fixes";
        metadata.description = "I hack other people's mods, okay?! Baka!";
        metadata.version = "0.1.0";
        metadata.authorList = Arrays.asList(AUTHORS);
        metadata.autogenerated = false;
        return metadata;
    }

    public static final String[] AUTHORS;

    static {
        AUTHORS = new String[] { "da3dsoul" };
    }
}
